local_costmap:
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.04

  plugins:
    - {name: local_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}




